apiVersion: build.pivotal.io/v1alpha1
kind: Image
metadata:
  name: dotnet-api
  namespace: kpack-builders
spec:
  tag: pkhamdee/dotnet-api:2.2.2
  serviceAccount: kpack-service-account
  builder:
    name: custom-dotnetcore-builder
    kind: CustomBuilder
  cacheSize: "2Gi"
  source:
    git:
      url: https://github.com/pkhamdee/dotnet-api.git
      revision: release
